#!/bin/python3

import math
import os
import random
import re
import sys

if __name__ == '__main__':
    n = int(input().strip())
    for i in range(1,11): #for loop is added to decare the range
      print(n, 'x', i, '=', n*i) #multipication format
